# Generated by Django 4.2.4 on 2023-12-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_block', models.TextField(editable=False)),
                ('item_id', models.TextField(max_length=3)),
                ('type_id', models.TextField(max_length=3)),
            ],
        ),
    ]
