# Generated by Django 4.2.4 on 2023-12-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='html_block',
            field=models.TextField(),
        ),
    ]
