# Generated by Django 4.2.4 on 2023-12-08 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_alter_template_html_block'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Template',
        ),
    ]
